SELECT
  *
FROM
  "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA";

  SELECT *
FROM CAR_SALES_DATA;


  --how many cars were sold
  SELECT COUNT(*) AS total_cars_sold
FROM  "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA";

--Total revenue from all car sales
SELECT SUM (sellingprice) AS total_revenue
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA";

--Top 5 car brands by revenue
SELECT Make, SUM(sellingprice) AS revenue
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
GROUP BY Make
ORDER BY revenue DESC;

--Average price by year
SELECT Year, AVG(sellingprice) AS average_price
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
GROUP BY Year
ORDER BY Year;

DESC TABLE "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA";

-- Sales by region (state)
SELECT STATE, COUNT(*) AS cars_sold, SUM(SELLINGPRICE) AS revenue
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
GROUP BY STATE
ORDER BY revenue DESC;

--Price vs. mileage groups
SELECT
  CASE
    WHEN ODOMETER < 20000 THEN '0–20k'
    WHEN ODOMETER < 50000 THEN '20–50k'
    WHEN ODOMETER < 100000 THEN '50–100k'
    WHEN ODOMETER < 150000 THEN '100–150k'
    ELSE '150k+'
  END AS mileage_group,
  AVG(SELLINGPRICE) AS average_price,
  COUNT(*) AS cars_in_group
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
GROUP BY mileage_group
ORDER BY cars_in_group DESC;

--Monthly price trends
SELECT
  DATE_TRUNC('MONTH', TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS sale_month,
  AVG(SELLINGPRICE) AS average_price,
  COUNT(*) AS cars_sold
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
WHERE SALEDATE IS NOT NULL
GROUP BY sale_month
ORDER BY sale_month;

--Transmission type preference
SELECT TRANSMISSION, COUNT(*) AS car_count
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA"
GROUP BY TRANSMISSION
ORDER BY car_count DESC;

CREATE OR REPLACE VIEW "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_CLEAN" AS
SELECT
  YEAR,
  MAKE,
  MODEL,
  TRIM,
  BODY,
  TRANSMISSION,
  VIN,
  STATE,
  CONDITION,
  ODOMETER,
  COLOR,
  INTERIOR,
  SELLER,
  MMR,
  SELLINGPRICE,
  SALEDATE,
  DATE_TRUNC('MONTH', TO_TIMESTAMP(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS SALE_MONTH,
  CASE
    WHEN ODOMETER < 20000 THEN '0–20k'
    WHEN ODOMETER < 50000 THEN '20–50k'
    WHEN ODOMETER < 100000 THEN '50–100k'
    WHEN ODOMETER < 150000 THEN '100–150k'
    ELSE '150k+'
  END AS MILEAGE_BIN
FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_DATA";


SELECT * FROM "BRIGHT_MOTORS_CAR_SALES_ANALYSIS"."CAR_SALES"."CAR_SALES_CLEAN";










